name: actors
description: Actors Model library for Dart.
version: 0.1.0
homepage: https://github.com/renatoathaydes/actors
author: Renato Athaydes <renato@athaydes.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
